#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:3001/eureka/
      
spring:
  application:
    name: stock-service-auth
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  datasource:
    url: jdbc:mysql://192.168.0.106:3306/stock?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    discovery:
      enabled: false

server:
  port: 3002
  
  
jwt:
  header: Authorization
  secret: mySecret
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI
  expiration: 604800
  token-validity-in-seconds: 86400
  token-validity-in-seconds-for-remember-me: 108000
  route:
    authentication:
      path: /auth
      refresh: /refresh